//
// Created by marin on 14/04/2024.
//

#ifndef THRESHOLDS_H
#define THRESHOLDS_H


#define SPEED_ZERO 0.1
#define SPEED_MIN_ASCENT 0.1
#define ALTITUDE_MAX 9000
#define ALTITUDE_ZERO 10
#define LOX_PRESSURE_WANTED 0.1
#define LOX_PRESSURE_ZERO 0.1
#define LOX_PRESSURE_MAX 0.1
#define FUEL_PRESSURE_WANTED 0.1
#define FUEL_PRESSURE_ZERO 0.1
#define FUEL_PRESSURE_MAX 0.1
#define CHAMBER_PRESSURE_WANTED 0.1
#define CHAMBER_PRESSURE_ZERO 0.1
#define ENGINE_TEMP_ZERO 0.1
#define ENGINE_TEMP_WANTED 0.1
#define INJECTOR_PRESSURE_WANTED_MIN 0.1
#define INJECTOR_PRESSURE_WANTED_MAX 0.1
#define INJECTOR_PRESSURE_ZERO 0.1
#define FUEL_INJ_ZERO 0.1
#define LOX_LEVEL_ZERO 0.1
#define LOX_LEVEL_FULL 0.1
#define FUEL_LEVEL_ZERO 0.1
#define FUEL_LEVEL_FULL 0.1
#define N2_PRESSURE_ZERO 0.1
#define ACCEL_ZERO 0.1
#define ACCEL_LIFTOFF 0.1
#define IGNITER_PRESSURE_WANTED 0.1
#define IGNITER_PRESSURE_ZERO 0.1
#define ALTITUDE_THRESHOLD 300
#define PRESSURIZATION_WAIT_TIME 10000 //in ms
#define OVERPRESSURE_GRACE_MS  80 //in ms
#define BUFFER_ACCEL_TIME 500 //in ms
#define MAX_LIFTOFF_TIMEOUT 10000 //in ms

#endif //THRESHOLDS_H

