//
// Created by marin on 14/04/2024.
//

#ifndef THRESHOLDS_H
#define THRESHOLDS_H


#define SPEED_ZERO 0.1
#define ALTITUDE_MAX 9000
#define ALTITUDE_ZERO 10
#define LOX_PRESSURE_WANTED 0.1
#define LOX_PRESSURE_ZERO 0.1
#define FUEL_PRESSURE_WANTED 0.1
#define FUEL_PRESSURE_ZERO 0.1
#define CHAMBER_PRESSURE_WANTED 0.1
#define CHAMBER_PRESSURE_ZERO 0.1
#define ENGINE_TEMP_ZERO 0.1
#define ENGINE_TEMP_WANTED 0.1
#define INJECTOR_PRESSURE_WANTED_MIN 0.1
#define INJECTOR_PRESSURE_WANTED_MAX 0.1
#define INJECTOR_PRESSURE_ZERO 0.1
#define FUEL_INJ_ZERO 0.1
#define LOX_LEVEL_ZERO 0.1
#define LOX_LEVEL_FULL 0.1
#define FUEL_LEVEL_ZERO 0.1
#define FUEL_LEVEL_FULL 0.1
#define N2_PRESSURE_ZERO 0.1
#define ACCEL_ZERO 0.1
#define IGNITER_PRESSURE_WANTED 0.1
#define IGNITER_PRESSURE_ZERO 0.1
#define ALTITUDE_THRESHOLD 300

#endif //THRESHOLDS_H

