name: Check Tests

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed


jobs:
  check-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check the status of the tests
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
            echo "Tests failed"
            exit 1
          fi