
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Configure and Build
        run: |
          cd build
          cmake ..
          make
      - name: Run Test Executables
        run: |
          ls build
          
