name: Raspberry Pi CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull PI-CI Docker image
        run: docker pull ptrsr/pi-ci

      - name: Build and test
        run: |
          docker run --rm -v $PWD:/workspace ptrsr/pi-ci start