name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install pigpio library
        run: sudo apt-get install pigpio

      - name: Install g++
        run: sudo apt-get install g++









  
