
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
          sudo apt-get install -y build-essential
          sudo apt-get install pigpio
      - name: Configure and Build
        run: |
          cd build
          cmake ..
          make
      - name: Run Test Executables
        run: |
          ls build
          
