name: Raspberry Pi CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# build docker image and compile the code in it

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Compile code
        run: docker run --rm -v $PWD:/app myapp make











  
