
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          base_image: raspios_lite:2022-04-04
          commands: |
            cd build
            cmake ..
            make
            
