
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Tests on Raspberry Pi 4B
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite:2022-04-04
          commands: |
            sudo apt-get update
            sudo apt-get install -y gcc
            sudo apt-get install -y g++
            sudo apt-get install -y make
            sudo apt-get install -y cmake
            sudo apt-get install -y pigpio
            
            cd build
            cmake ..
            make
            
            ls
            
            ./ADXL375_test
            ./BMI088_test
            ./BMP390_test
            
            
