name: CI

on:
  push:
    branches:
      - main  # adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest  # or choose an appropriate runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-qemu-action@v1

      - name: Pull Docker Image
        run: docker pull stawiski/qemu-raspberrypi-3b:2023-05-03-raspios-bullseye-arm64

      - name: Run Docker Container
        run: docker run -it --rm -p 2222:2222 stawiski/qemu-raspberrypi-3b:2023-05-03-raspios-bullseye-arm64