
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_base_images:
    strategy:
      fail-fast: false
      matrix:
        image:

          - raspi_4_bullseye:20230102
          - raspi_4_bookworm:20230101
          - raspi_4_bookworm:20230612
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./ # pguyot/arm-runner-action@HEAD
        with:
          base_image: ${{ matrix.image }}
          cpu: cortex-a7
          commands: |
            cat /etc/os-release
            uname -a
