name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up cross-compilation toolchain
        run: |
          # Install ARM cross-compilation toolchain (example)
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install pigpio library
        run: |
          # Install pigpio library on the host machine (example)
          wget https://github.com/joan2937/pigpio/archive/master.zip
          unzip master.zip
          cd pigpio-master
          make
          sudo make install

      - name: Build the project
        run: |
          # Cross-compile the project (example)
          cd build
          cmake ..
          make

      - name: Run the tests
        run: |
            ./ADXL345_test
            ./HMC5883L_test
            ./ITG3200_test
          









  
