name: Trigger Tests

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened



jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger tests repository
        id: trigger
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: EPFLRocketTeam/C_AV_SIL
          event-type: run-tests
          client-payload: |
            {
              "branch": "${{ github.head_ref }}",
              "commit": "${{ github.sha }}",
              "repo": "${{ github.repository }}"
            }

    
      
